name: mbuild-binder

channels:
  - conda-forge
  - defaults
  - mosdef
  - omnia

dependencies:
  - python>=3.6
  - numpy
  - scipy
  - packmol>=1!18.013
  - nglview>=0.6.2.3
  - oset
  - parmed
  - mdtraj
  - gsd
  - openbabel
  - jupyter
  - nbformat
  - six
  - foyer
  - py3Dmol
